Minor docs update
rs-station/laue-dials pull request #36
Opened 2023-11-08 19:19 UTC by dennisbrookner

So far in this PR, I have
 - reordered the pages on the website so that the command-line reference comes first
 - added a placeholder "coming soon!" tutorial page, where we can add the tutorial in markdown format.

I figure we can leave this PR open while the tutorial continues to take shape.

2023-11-15 18:49 UTC, PrinceWalnut commented
I have a couple of edits to make to the notebook based on feedback from Maggie Klureza. I'll make sure to push them by end of week, and perhaps we can include the tutorial into this PR. Let me know if you want to take that on, and what format would be easiest for you to work with @dennisbrookner.

2025-06-17 17:01 UTC, PrinceWalnut commented
Considerably updated all the docs and included some small tweaks to update code (deprecated Gemmi cell.fractionalization_matrix comes to mind). The online documentation has been reworked and online `.rst` files are now used in place of Jupyter notebooks.

2025-06-17 20:16 UTC, kmdalton requested changes
I can do a more thorough review later, but there a few things i noticed that merit changes.

2025-06-17 20:51 UTC, PrinceWalnut commented on docs/tutorials/hewl/HEWL_anom_laue_dials_processing_final_rst.rst
> +.. code:: ipython3
These `.rst` files were created using `nbconvert`, but you're right, it appears not to remove the magics. I'll fix this manually for now, but we should figure out a way to automate converting Jupyter notebooks into `.rst` files conveniently for any future tutorials and/or edits to present tutorials.

2025-06-17 21:02 UTC, PrinceWalnut commented on CONTRIBUTING.rst
> +1. Create a file in the ``docs/cli/`` directory called ``{function-name}.rst``. The contents of this file should match the contents of the other ``.rst`` files in this directory, using the new functi
Sphinx (through `docutils` requires that the underline be at least as long as the header text, or 4 characters, whichever is greater. It appears to output a warning emitted by `docutils` if this doesn't occur. Not sure if this breaks the build or just fills the logs with warnings -- will test shortly and update this doc accordingly.

2025-06-17 21:03 UTC, PrinceWalnut commented on AUTHORS.rst
> +Vukica Srajer
Thanks, fixed

2025-06-18 16:06 UTC, PrinceWalnut commented on docs/tutorials/hewl/HEWL_anom_laue_dials_processing_final_rst.rst
> +.. code:: ipython3
Should be resolved. Still need to embed plots, but the code should no longer be an issue.

2025-06-18 16:14 UTC, kmdalton commented
ping me when you want another review. it sounds like you've got a couple more items to include in this PR. thanks!

2025-07-08 21:36 UTC, kmdalton requested changes
I made one small suggestion. I was able to build the docs locally following the new instructions with `make`. They look good to me, but I haven't read the translated tutorials in detail.

2025-07-08 21:36 UTC, kmdalton commented on README.rst
> +https://rs-station.github.io/laue-dials/index.html. For the Github repository, please visit
Minor suggestion: "For source code, please visit ..."

2025-07-15 17:43 UTC, LuisA92 commented on docs/index.rst
I noticed that both “Contents” and “Indices and tables” appear as separate entries in the sidebar, but they both point to the same page ([index.rst](https://rs-station.github.io/laue-dials/tutorials/notebooks.html#)).

2025-07-15 18:24 UTC, LuisA92 commented on docs/tutorials/hewl/HEWL_anom_laue_dials_processing_final_rst.rst
> +     anomalous peak heights for each I and S atom accross all frame
Typo: should be "across" instead of "accross"

2025-07-15 18:25 UTC, LuisA92 commented on docs/tutorials/hewl/HEWL_anom_laue_dials_processing_final_rst.rst
> +crystal and be downloaded `on SBGrid <https://data.sbgrid.org/dataset/1118/>`__.
Typo: I think this should read "and **can** be downloaded"

2025-07-15 18:30 UTC, LuisA92 commented on docs/tutorials/pdz2/tutorial_combine_passes_rst.rst
> +then the crystal is rotated aaround the phi goniometer axis and then the
Typo: "around" instead of "aaround"

2025-07-23 16:34 UTC, merged